name: Build Kivy APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Buildozer & dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          ccache \
          git \
          zip \
          unzip \
          openjdk-8-jdk \
          python3-pip \
          python3-setuptools \
          python3-wheel \
          python3-venv \
          libncurses5 \
          libncurses5-dev \
          libstdc++6 \
          lib32z1 \
          libbz2-1.0 \
          libz1:i386 \
          libstdc++6:i386 \
          zlib1g:i386

        sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/java-8-openjdk-amd64/bin/java 1
        sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/bin/java

        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

        pip install --upgrade pip
        pip install cython buildozer

    - name: Initialize Buildozer (if needed)
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi

    - name: Accept Android SDK licenses
      run: |
        yes | buildozer android update

    - name: Build APK with Buildozer
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: galaxy-apk
        path: bin/*.apk
