name: Build Kivy APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: $HOME/Android/Sdk
      PATH: $HOME/Android/Sdk/cmdline-tools/latest/bin:$HOME/Android/Sdk/platform-tools:$HOME/Android/Sdk/build-tools/34.0.0:$PATH

    steps:
    - name: Ensure tar is installed
      run: sudo apt-get update && sudo apt-get install -y tar

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools python3-wheel \
          build-essential libssl-dev libffi-dev python3-dev \
          python3-venv openjdk-8-jdk git \
          libncurses5-dev libstdc++6 lib32z1 libbz2-1.0 wget unzip

    - name: Install Android SDK and Build Tools
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest

        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "build-tools;34.0.0" "platforms;android-34"

        echo "AIDL check:"
        ls $ANDROID_HOME/build-tools/34.0.0/aidl || echo "AIDL not found!"

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install cython
        pip install buildozer

    - name: Initialize Buildozer and configure spec
      run: |
        if [ ! -f buildozer.spec ]; then
          buildozer init
        fi
        sed -i 's/^android.api = .*/android.api = 34/' buildozer.spec
        sed -i 's/^# android.build_tools_version = .*/android.build_tools_version = 34.0.0/' buildozer.spec
        sed -i 's/^# android.sdk_path = .*/android.sdk_path = \$HOME\/Android\/Sdk/' buildozer.spec

    - name: Build APK with Buildozer
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: galaxy-apk
        path: bin/*.apk
