name: Build Kivy APK

# Trigger manually using GitHub UI
on:
  workflow_dispatch:  # This allows manual triggering from GitHub UI

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Checkout repository contents

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'  # Specify the Python version used in your project

    - name: Install Buildozer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-setuptools python3-wheel
        sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev
        sudo apt-get install -y python3-venv
        pip install --upgrade pip
        pip install buildozer  # Install buildozer to build the APK

    - name: Install Android dependencies
      run: |
        sudo apt-get install -y openjdk-8-jdk  # Install the correct JDK
        sudo apt-get install -y git  # Make sure Git is installed for Buildozer
        sudo apt-get install -y libncurses5 libstdc++6 lib32z1 libbz2-1.0

    - name: Configure Buildozer
      run: |
        # Optional: You can modify buildozer.spec before running the build.
        echo "Custom buildozer config adjustments go here if needed"

    - name: Build APK with Buildozer
      run: |
        buildozer android debug  # This triggers Buildozer to start building the APK

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: galaxy-apk
        path: bin/galaxy-debug.apk  # Adjust this to match where your APK is stored

