name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential ccache git zip unzip \
          openjdk-17-jdk python3-pip python3-setuptools \
          python3-wheel python3-virtualenv libffi-dev \
          libssl-dev libsqlite3-dev libjpeg-dev zlib1g-dev \
          libncurses6 libstdc++6

    - name: Install buildozer
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    - name: Initialize buildozer
      run: |
        buildozer init || echo "buildozer.spec already exists"

    - name: Accept Android SDK licenses
      run: |
        yes | ~/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses || true

      env:
        PATH: $HOME/.buildozer/android/platform/android-sdk/cmdline-tools/latest/bin:$PATH

    - name: Build APK
      run: buildozer android debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: galaxy-game-apk
        path: bin/*.apk
